### PR TITLE
Benchmark 5950X

### PR DESCRIPTION
**Pull request by SK-FComputer**
Created benchmark on AMD Ryzen 9 5950X 16-Core Processor
Background work while running, so not fully clean.

Might do after work

### CODE REVIEW

**Comment by samchon** [comment]
Even slower than my surface pro 8 (i5).

Possible to run again in clean env?

**Comment by SK-FComputer** [comment]
Ran again with clean ENV:
Stopped all background/foreground programs, docker containers etc.

Not much gained by that in terms of raw 1:1 performance

**Review by samchon — APPROVED** [review]
Thanks for your contribution.

Please understand if some faster 5950x comes, then the benchmark result can be overwritten.

**Comment by SK-FComputer** [comment]
Taking a quick look at current results:
Seems like Typia prefers Windows, and Intel processors

If benchmarks is correct, some fluctuate very much

**Comment by samchon** [comment]
It is not a benchmark with strict variable control, but a benchmark that PR just believes and accepts, so reliability may be somewhat lower.

**Pull request merged**
