### PR TITLE
fix: merge installation with setup

### PR DESCRIPTION
**Pull request by seo-rii**
Embedded `npm install typia` into `npx typia setup`.

### CODE REVIEW

**Comment by samchon** [comment]
The `npx typia setup` command works only when `typia` being installed.

Its because `npx` command with setup works only when there's not any dependency, but `typia`'s CLI require them:

  - `commander`
  - `comment-json`
  - `inquireer`

**Review by samchon — COMMENTED** [review]
The `npx typia setup` command works only when `typia` being installed.

Its because `npx` command with setup works only when there's not any dependency, but `typia`'s CLI require them:

  - `commander`
  - `comment-json`
  - `inquireer`

**Comment by seo-rii** [comment]
I believe that latest version of npx resolves dependency automatically. I tested it in clean docker enviornment, and setup succeeded without typia installation. I'll attach my log.

```sh
seo_hyun@iseohyeon-ui-MacBookAir ~ % docker run -it -d node:alpine
7865837fdaa5b5d511a391a4bf6802ee09d3fef5fae53e895c498e4edc990367
seo_hyun@iseohyeon-ui-MacBookAir ~ % docker container ls
CONTAINER ID   IMAGE         COMMAND                  CREATED         STATUS         PORTS     NAMES
7865837fdaa5   node:alpine   "docker-entrypoint.s…"   4 seconds ago   Up 3 seconds             frosty_euclid
seo_hyun@iseohyeon-ui-MacBookAir ~ % docker exec -it frosty_euclid bash
OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
seo_hyun@iseohyeon-ui-MacBookAir ~ % docker exec -it frosty_euclid sh  
/ # pwd
/
/ # mkdir test
/ # cd test
/test # npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help init` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (test) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /test/package.json:

{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this OK? (yes) 
npm notice 
npm notice New minor version of npm available! 10.2.4 -> 10.4.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.4.0
npm notice Run npm install -g npm@10.4.0 to update!
npm notice 
/test # npx typia setup
Need to install the following packages:
typia@5.4.9
Ok to proceed? (y) y
----------------------------------------
 Typia Setup Wizard
----------------------------------------
? Package Manager npm


$ npm install --save-dev ts-patch@latest

added 24 packages, and audited 25 packages in 3s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npm install --save-dev ts-node@latest

added 20 packages, and audited 45 packages in 5s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npm install --save-dev typescript@5.3.2

changed 1 package, and audited 45 packages in 2s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npx tsc --init

Created a new tsconfig.json with:                                                                                       
                                                                                                                     TS 
  target: es2016
  module: commonjs
  strict: true
  esModuleInterop: true
  skipLibCheck: true
  forceConsistentCasingInFileNames: true


You can learn more at https://aka.ms/tsconfig

$ npm run prepare

> test@1.0.0 prepare
> ts-patch install && typia patch

[+] ts-patch installed!
----------------------------------------
 Typia Setup Wizard
----------------------------------------
Since TypeScript v5.3 update, "tsc" no more parses JSDoc comments.

Therefore, "typia" revives the JSDoc parsing feature by patching "tsc".

This is a temporary feature of "typia", and it would be removed when "ts-patch" being updated.
/test # nano package.json
sh: nano: not found
/test # cat package.json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "prepare": "ts-patch install && typia patch"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "ts-node": "^10.9.2",
    "ts-patch": "^3.1.2",
    "typescript": "^5.3.2"
  }
/test # apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/aarch64/APKINDEX.tar.gz
v3.19.1-113-g898386b9cbc [https://dl-cdn.alpinelinux.org/alpine/v3.19/main]
v3.19.1-124-gf4fe8bcb5b2 [https://dl-cdn.alpinelinux.org/alpine/v3.19/community]
OK: 22844 distinct packages available
/test # apk add nano
(1/3) Installing ncurses-terminfo-base (6.4_p20231125-r0)
(2/3) Installing libncursesw (6.4_p20231125-r0)
(3/3) Installing nano (7.2-r1)
Executing busybox-1.36.1-r15.trigger
OK: 11 MiB in 20 packages
/test # nano index.ts
/test # cat index.ts
import typia from "typia"

console.log(typia.is<number>(1));
/test # npm i typia

added 55 packages, and audited 100 packages in 1s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/test # ts-node index.ts
sh: ts-node: not found
/test # npx ts-node index.ts
true
/test # 
```

**Comment by samchon** [comment]
Wow, I haven't known that.

By the way, as I have to consider the older version users, I can't accept it right now.

**Comment by seo-rii** [comment]
It seems npx automatically resolves dependencies from npm v7, which is deployed with node v15.

**Comment by seo-rii** [comment]
How about merging this in April, which is original date of node v16 depreciation?

**Comment by samchon** [comment]
Well, right now, no plan to merge due to local install is not bad (`npx typia` without local install leads to global setup). If `typia` had separated CLI and core library, I think your PR may valid. However, as you know, `typia` have both of them.

Instead, this strategy seems much proper for `nestia` and `@nestia/migrate `case. Unlike `typia` which contains both core library and setup program in the same module, `nestia` has separated CLI and core library. Also, `@nestia/migrate` is actually required to perform the global setup.

Can you send a same PR to there?

- https://nestia.io/docs/setup/
- https://nestia.io/docs/migrate/
- https://nestia.io/docs/editor/

**Pull request closed without merging**
