### PR TITLE
Add benchmark of AMD 5800H

### PR DESCRIPTION
**Pull request by devfrank9**
Before submitting a Pull Request, please test your code. 

If you created a new created a new feature, then create the unit test function, too.

```bash
# COMPILE THE BACKEND SERVER
npm run build

# RUN THE TEST AUTOMATION PROGRAM
npm run test
```

Learn more about the [CONTRIBUTING](CONTRIBUTING.md)

### CODE REVIEW

**Review by samchon — CHANGES_REQUESTED** [review]
Can you run the benchmark program again with below command?

Also, you should check your notebook is on charging.

Your benchmark result is extremely different with my 5800H.

```bash
npm run build:test
npm run benchmark
```

**Comment by devfrank9** [comment]
2 command run and my laptop is charging

**Comment by samchon** [comment]
Well, need more investigation about this PR.

Therefore, would be hold.

**Review by samchon — COMMENTED** [review]
Well, need more investigation about this PR.

Unable to understand reason why about such great different between two same CPUs.

Therefore, hold this for a while.

Anway, can you tell me your laptop's full name?

**Comment by devfrank9** [comment]
HP 15-ec2122AX
image

**Pull request closed without merging**
