### PR TITLE
feat(rollup.config): improve tree-shaking using `preserveModules: true`

### PR DESCRIPTION
**Pull request by ryoppippi**
Related to #1128 
I fixed the import path of randexp

### CODE REVIEW

**Comment by ryoppippi** [comment]
After merging this pr https://github.com/samchon/typia/pull/1134 , you can easily check the build result

**Comment by ryoppippi** [comment]
@samchon 
Any update on this?

**Comment by samchon** [comment]
Will check this at Wednesday.

**Review by samchon — CHANGES_REQUESTED** [review]
Checked your PR, but it still makes invalid import path.

```javascript
import RandExp from '../../_external/.pnpm/randexp@0.5.3/node_modules/randexp/lib/randexp.mjs';

const ALPHABETS = "abcdefghijklmnopqrstuvwxyz";
/* -----------------------------------------------------------
  REGULAR
----------------------------------------------------------- */
const boolean = () => Math.random() < 0.5;
const integer = (min, max) => {
    min ??= 0;
    max ??= 100;
    return Math.floor(Math.random() * (max - min + 1)) + min;
};
const bigint = (min, max) => BigInt(integer(Number(min ?? BigInt(0)), Number(max ?? BigInt(100))));
const number = (min, max) => {
    min ??= 0;
    max ??= 100;
    return Math.random() * (max - min) + min;
};
const string = (length) => new Array(length ?? integer(5, 10))
    .fill(0)
    .map(() => ALPHABETS[integer(0, ALPHABETS.length - 1)])
    .join("");
const array = (closure, count) => new Array(count ?? length()).fill(0).map((_e, index) => closure(index));
const pick = (array) => array[integer(0, array.length - 1)];
const length = () => integer(0, 3);
const pattern = (regex) => {
    const r = new RandExp(regex);
    for (let i = 0; i < 10; ++i) {
        const str = r.gen();
        if (regex.test(str))
            return str;
    }
    return r.gen();
};
/* -----------------------------------------------------------
  SECIAL FORMATS
----------------------------------------------------------- */
// SPECIAL CHARACTERS
const byte = () => "vt7ekz4lIoNTTS9sDQYdWKharxIFAR54+z/umIxSgUM=";
const password = () => string(integer(4, 16));
const regex = () => "/^(?:(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)\\.){3}(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)$/";
const uuid = () => "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
});
// ADDRESSES
const email = () => `${string(10)}@${string(10)}.${string(3)}`;
const hostname = () => `${string(10)}.${string(3)}`;
const idnEmail = () => email();
const idnHostname = () => hostname();
const iri = () => url();
const iriReference = () => url();
const ipv4 = () => array(() => integer(0, 255), 4).join(".");
const ipv6 = () => array(() => integer(0, 65535).toString(16), 8).join(":");
const uri = () => url();
const uriReference = () => url();
const uriTemplate = () => url();
const url = () => `https://${string(10)}.${string(3)}`;
// TIMESTAMPS
const datetime = (min, max) => new Date(number(min ?? Date.now() - 30 * DAY, max ?? Date.now() + 7 * DAY)).toISOString();
const date = (min, max) => new Date(number(min ?? 0, max ?? Date.now() * 2))
    .toISOString()
    .substring(0, 10);
const time = () => new Date(number(0, DAY)).toISOString().substring(11);
const duration = () => {
    const period = durate([
        ["Y", integer(0, 100)],
        ["M", integer(0, 12)],
        ["D", integer(0, 31)],
    ]);
    const time = durate([
        ["H", integer(0, 24)],
        ["M", integer(0, 60)],
        ["S", integer(0, 60)],
    ]);
    if (period.length + time.length === 0)
        return "PT0S";
    return `P${period}${time.length ? "T" : ""}${time}`;
};
// POINTERS
const jsonPointer = () => `/components/schemas/${string(10)}`;
const relativeJsonPointer = () => `${integer(0, 10)}#`;
const DAY = 86400000;
const durate = (elements) => elements
    .filter(([_unit, value]) => value !== 0)
    .map(([unit, value]) => `${value}${unit}`)
    .join("");

export { array, bigint, boolean, byte, date, datetime, duration, email, hostname, idnEmail, idnHostname, integer, ipv4, ipv6, iri, iriReference, jsonPointer, length, number, password, pattern, pick, regex, relativeJsonPointer, string, time, uri, uriReference, uriTemplate, url, uuid };
//# sourceMappingURL=RandomGenerator.mjs.map
```

**Comment by ryoppippi** [comment]
Oh, really? I'll check it

**Comment by ryoppippi** [comment]
I'll check after this PR solves https://github.com/samchon/typia/pull/1142

**Comment by ryoppippi** [comment]
@samchon 
so, you can install this PR from this link https://github.com/samchon/typia/pull/1133#issuecomment-2202890690 !

I installed this and checked it on my local environment.
As you can see, the `RandExp` path is correct
```ts
import RandExp from '../../_external/randexp/lib/randexp.mjs';

```

idk why it is not working in your enviroment.
Maybe because of pnpm??

**Comment by samchon** [comment]
Understood, it was not a bug in `npm`, but only the problem of `pnpm`.

By the way, previous `typia` had generated only one `index.mjs` file, and your new PR contribution makes multiple `mjs` files for every TS files. 

As far as I know, number of files does not affetct to esm tree shaking. Therefore, I am not sure if the actual bundling size is correct as the number of files increases.

**Comment by ryoppippi** [comment]
Ohhhh I got it 
so, when using `npm` or `bun`, the package is installed in flat structure,
so the external path is like this
```
node_modules/randexp/lib/randexp
node_modules/ret/lib/index
node_modules/drange/lib/index
node_modules/ret/lib/util
node_modules/ret/lib/types
node_modules/ret/lib/sets
node_modules/ret/lib/positions
```

However, pnpm is different structure, and the path looks like this

```
node_modules/.pnpm/randexp@0.5.3/node_modules/randexp/lib/randexp
node_modules/.pnpm/ret@0.2.2/node_modules/ret/lib/index
node_modules/.pnpm/drange@1.1.1/node_modules/drange/lib/index
node_modules/.pnpm/ret@0.2.2/node_modules/ret/lib/util
node_modules/.pnpm/ret@0.2.2/node_modules/ret/lib/types
node_modules/.pnpm/ret@0.2.2/node_modules/ret/lib/sets
node_modules/.pnpm/ret@0.2.2/node_modules/ret/lib/positions
```

Anyway I'll add support for pnpm

**Comment by samchon** [comment]
Then no way to solve the problem in the `pnpm` through rollup configuration?

**Comment by ryoppippi** [comment]
@samchon 
I'm implementing configuration.


Also, I investigated that this improves tree-shaking.
I'll show you an example after fix this

**Comment by ryoppippi** [comment]
@samchon 
I fixed the build config.

Also, I created an experiment enviroment.
https://stackblitz.com/edit/vitejs-vite-twjepx?file=package.json
https://stackblitz.com/edit/vitejs-vite-d7cpuz?file=package.json


Why do these differences occur?
Because re-exported namespaces cannot be tree-shaked.

https://github.com/evanw/esbuild/issues/1420

If you bundle the js files into single file, the named exports are converted into objects, so that bundlers cannnot identify those methods in the objects are from real object or named export from other files.
However, when we split the js files, bundlers can identify these differences

**Comment by samchon** [comment]
Great. I'll publish it to v3.5.0 at tomorrow.

> Waiting for `@samchon/openapi` dependency update.

Also, your github sponsorship dashboard configuration is not yet?

**Comment by ryoppippi** [comment]
Not yet Please wait

**Comment by samchon** [comment]
@ryoppippi Now, I've completed `@samchon/openapi` upgrade, so that ready to publish `typia@6.4.0`.

May I publish v6.4 now, or do you have something more to do about the tree shake bundling?

**Comment by ryoppippi** [comment]
For now it is fine!
Thanks!!
Please publish it!

**Comment by samchon** [comment]
It still makes invalid path in `pnpm`.

```javascript
import RandExp from '../../_external/node_modules_.pnpm_randexp@0.5.3_node_modules_randexp_lib/randexp.mjs';

const ALPHABETS = "abcdefghijklmnopqrstuvwxyz";
/* -----------------------------------------------------------
  REGULAR
----------------------------------------------------------- */
const boolean = () => Math.random() < 0.5;
const integer = (min, max) => {
    min ??= 0;
    max ??= 100;
    return Math.floor(Math.random() * (max - min + 1)) + min;
};
const bigint = (min, max) => BigInt(integer(Number(min ?? BigInt(0)), Number(max ?? BigInt(100))));
const number = (min, max) => {
    min ??= 0;
    max ??= 100;
    return Math.random() * (max - min) + min;
};
const string = (length) => new Array(length ?? integer(5, 10))
    .fill(0)
    .map(() => ALPHABETS[integer(0, ALPHABETS.length - 1)])
    .join("");
const array = (closure, count, unique) => {
    count ??= length();
    unique ??= false;
    if (unique === false)
        return new Array(count ?? length())
            .fill(0)
            .map((_e, index) => closure(index));
    else {
        const set = new Set();
        while (set.size < count)
            set.add(closure(set.size));
        return Array.from(set);
    }
};
const pick = (array) => array[integer(0, array.length - 1)];
const length = () => integer(0, 3);
const pattern = (regex) => {
    const r = new RandExp(regex);
    for (let i = 0; i < 10; ++i) {
        const str = r.gen();
        if (regex.test(str))
            return str;
    }
    return r.gen();
};
/* -----------------------------------------------------------
  SECIAL FORMATS
----------------------------------------------------------- */
// SPECIAL CHARACTERS
const byte = () => "vt7ekz4lIoNTTS9sDQYdWKharxIFAR54+z/umIxSgUM=";
const password = () => string(integer(4, 16));
const regex = () => "/^(?:(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)\\.){3}(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)$/";
const uuid = () => "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
});
// ADDRESSES
const email = () => `${string(10)}@${string(10)}.${string(3)}`;
const hostname = () => `${string(10)}.${string(3)}`;
const idnEmail = () => email();
const idnHostname = () => hostname();
const iri = () => url();
const iriReference = () => url();
const ipv4 = () => array(() => integer(0, 255), 4).join(".");
const ipv6 = () => array(() => integer(0, 65535).toString(16), 8).join(":");
const uri = () => url();
const uriReference = () => url();
const uriTemplate = () => url();
const url = () => `https://${string(10)}.${string(3)}`;
// TIMESTAMPS
const datetime = (min, max) => new Date(number(min ?? Date.now() - 30 * DAY, max ?? Date.now() + 7 * DAY)).toISOString();
const date = (min, max) => new Date(number(min ?? 0, max ?? Date.now() * 2))
    .toISOString()
    .substring(0, 10);
const time = () => new Date(number(0, DAY)).toISOString().substring(11);
const duration = () => {
    const period = durate([
        ["Y", integer(0, 100)],
        ["M", integer(0, 12)],
        ["D", integer(0, 31)],
    ]);
    const time = durate([
        ["H", integer(0, 24)],
        ["M", integer(0, 60)],
        ["S", integer(0, 60)],
    ]);
    if (period.length + time.length === 0)
        return "PT0S";
    return `P${period}${time.length ? "T" : ""}${time}`;
};
// POINTERS
const jsonPointer = () => `/components/schemas/${string(10)}`;
const relativeJsonPointer = () => `${integer(0, 10)}#`;
const DAY = 86400000;
const durate = (elements) => elements
    .filter(([_unit, value]) => value !== 0)
    .map(([unit, value]) => `${value}${unit}`)
    .join("");

export { array, bigint, boolean, byte, date, datetime, duration, email, hostname, idnEmail, idnHostname, integer, ipv4, ipv6, iri, iriReference, jsonPointer, length, number, password, pattern, pick, regex, relativeJsonPointer, string, time, uri, uriReference, uriTemplate, url, uuid };
//# sourceMappingURL=RandomGenerator.mjs.map
```

**Comment by samchon** [comment]
Oops, I'm sorry, it was not a bug.

**Comment by ryoppippi** [comment]
Yeah I managed to do it

**Comment by ryoppippi** [comment]
@samchon 
BTW, I enabled GH sponsorship rn !!!

https://github.com/ryoppippi

**Pull request merged**
