### PR TITLE
feat: Support ESM and CJS builds with esbuild

### PR DESCRIPTION
**Pull request by ryoppippi**
I made a tiny changes for build sources.

- support ESM because it enables tree shaking( solves https://github.com/samchon/typia/issues/1063)
- Build with `esbuild` instead of `tsc`, which makes build time faster

====
This commit introduces changes to support both ESM and CJS builds. The `package.json` file has been updated to include new build scripts and dependencies. Two new `tsconfig` files have been added for ESM and CJS respectively, and the original `tsconfig.json` has been removed. The `module` and `types` fields in `package.json` have been updated to point to the new ESM build.

Before submitting a Pull Request, please test your code. 

If you created a new feature, then create the unit test function, too.

```bash
# COMPILE
npm run build

# RE-WRITE TEST PROGRAMS IF REQUIRED
npm run test:template

# BUILD TEST PROGRAM
npm run build:test

# DO TEST
npm run test
```

Learn more about the [CONTRIBUTING](CONTRIBUTING.md)

### CODE REVIEW

**Comment by samchon** [comment]
Good idea, I'll try ESM rollup bundling on this branch after my job duty. 

Thanks for good suggestion

https://github.com/samchon/tgrid/blob/master/rollup.config.js

**Comment by ryoppippi** [comment]
@samchon 
Hi!
I'm tring tsup for bundle.
It is so good.
I'll create another PR for my idea.

**Comment by ryoppippi** [comment]
Also, I found some tree-shaking issues.
I'll create some PRs too.

**Comment by samchon** [comment]
Tried, but understood that, this change needs major update.

As `typia`'s internal utility functions are used in the `nestia` and other third party libraries, I have to take a major update.

If not, the `export` property of `package.json` would occur many problems.

Therefore, it would be take long time to adapt this suggestion \o/.

**Comment by samchon** [comment]
By the way, the next v7 update does not utilize namespace strategy more.

Instead, `typia` generates proper `import` statements only when required.

Therefore, please take this issue to me, then it would be fixed in someday.

https://github.com/samchon/typia/tree/features/import

**Pull request closed without merging**
