### PR TITLE
feat: Migrate to ESM and use rollup for building

### PR DESCRIPTION
**Pull request by ryoppippi**
## What's changed
This commit includes several changes:
- The package.json file has been updated to support ESM with the "type"
  field set to "module" and This commit includes several changes:
- The package.json file has been updated to support ESM with the "type"
  field set to "module" and the "exports" field properly configured.
- The build script in package.json has been changed to use tsup instead
  of tsc.
- tsup has been added as a devDependency.
- The tsconfig.json file has been simplified and updated for the new
  build process.
- A new tsup.config.js file has been added to configure the tsup build.

feat: Update build process and dependencies

This commit updates the build process by replacing `tsc --watch` with
`tsup --watch` in the `dev` script. It also removes the `tsp` section
from `package.json` and deletes `tsup.config.js`.

A new `tsup.config.ts` file is added which uses `fast-glob` and
`node:fs/promises` to handle TypeScript compilation and file renaming.
This is due to an issue with tsup's dts causing out of memory errors.

Additionally, `@microsoft/api-extractor` and `fast-glob` are added as
new devDependencies.Before submitting a Pull Request, please test your code. 

## Result
Here is the differnece of the bundle size

<details><summary>source code</summary>
<p>

```ts
import typia, {type tags} from 'typia'
interface Author {
  name: string;
  age:
    & number
    & tags.Type<"uint32">
    & tags.Minimum<20>
    & tags.ExclusiveMaximum<100>;
}
const validate = typia.createValidate<Author>();
console.log(validate({name: "John", age: 30}));
```

</p>
</details> 

Before
https://github.com/ryoppippi/typia-bundle-issue-repo/blob/8eb3cb8ec8dd8f8e9234aa2923cf352a73852c01/dist/index.js
```sh
~/p/typia-bundle main ❱ git id
8eb3cb8ec8dd8f8e9234aa2923cf352a73852c01
~/p/typia-bundle main ❱ ls -hlA dist_minify/ dist
dist_minify/:
Permissions Size User      Date Modified Name
.rw-r--r--   70k ryoppippi  3 Jun 17:28  index.js

dist:
Permissions Size User      Date Modified Name
.rw-r--r--  135k ryoppippi  3 Jun 17:28  index.js
```

After
https://github.com/ryoppippi/typia-bundle-issue-repo/blob/fb7bd4073cecafec84fa2e5f18656371e6df7cea/dist/index.js
```sh
~/p/typia-bundle feature/bundle-esm ❱ git id
fb7bd4073cecafec84fa2e5f18656371e6df7cea
~/p/typia-bundle feature/bundle-esm ❱ ls -hlA dist_minify/ dist
dist_minify/:
Permissions Size User      Date Modified Name
.rw-r--r--   45k ryoppippi  3 Jun 17:32  index.js

dist:
Permissions Size User      Date Modified Name
.rw-r--r--   87k ryoppippi  3 Jun 17:32  index.js
```
	
======================
If you created a new feature, then create the unit test function, too.

```bash
# COMPILE
npm run build

# RE-WRITE TEST PROGRAMS IF REQUIRED
npm run test:template

# BUILD TEST PROGRAM
npm run build:test

# DO TEST
npm run test
```

Learn more about the [CONTRIBUTING](CONTRIBUTING.md)the "exports" field properly configured.
- The build script in package.json has been changed to use tsup instead
  of tsc.
- tsup has been added as a devDependency.
- The tsconfig.json file has been simplified and updated for the new
  build process.
- A new tsup.config.js file has been added to configure the tsup build.

feat: Update build process and dependencies

This commit updates the build process by replacing `tsc --watch` with
`tsup --watch` in the `dev` script. It also removes the `tsp` section
from `package.json` and deletes `tsup.config.js`.

A new `tsup.config.ts` file is added which uses `fast-glob` and
`node:fs/promises` to handle TypeScript compilation and file renaming.
This is due to an issue with tsup's dts causing out of memory errors.

Additionally, `@microsoft/api-extractor` and `fast-glob` are added as
new devDependencies.Before submitting a Pull Request, please test your code. 

If you created a new feature, then create the unit test function, too.

```bash
# COMPILE
npm run build

# RE-WRITE TEST PROGRAMS IF REQUIRED
npm run test:template

# BUILD TEST PROGRAM
npm run build:test

# DO TEST
npm run test
```

Learn more about the [CONTRIBUTING](CONTRIBUTING.md)

### CODE REVIEW

**Comment by ryoppippi** [comment]
After that, I'm planning to create monorepo

**Comment by ryoppippi** [comment]
This PR does not resolve tree-shaking fully, but the bundle size is decreasing

**Review by samchon — CHANGES_REQUESTED** [review]
https://github.com/microsoft/TypeScript/issues/54276

Unfortunately, the transformer library like `typia` must be built with CJS, when considering the standard transform function that will be provided by the `Microsoft/TypeScript`.

Therefore, I'll try to change your commit, that can work properly with bundling, and also accomplish the bundling size diminishing. Thanks for considerations.

**Comment by ryoppippi** [comment]
@samchon 
Thank you for reviewing!!
I think this build script can also generate CJS script for tsconfig transform.
Did you try to build it?

**Comment by samchon** [comment]
Will commit to your repo soon. Wait for maybe five to ten minutes please.

Currently, I'm running test program, and it is working well even in the ESM.

**Comment by ryoppippi** [comment]
Thanks always

**Comment by samchon** [comment]
Changed to CJS, but ESM still be supported following your idea.

By the way, I'm sorry but I justed change something different with you:

1. Changed `tsup` to `rollup` because I'm only familiar with it. It is okay to change again.
    - No special reason for using `rollup`
    - It's just the reason why many libraries' developers are using that
2. About `tsx`, it can fully replace in current repo
    - However, `nestia` requires the `ts-node`
    - `tsx` can't replace the `ts-node` in the `nestia`
    - So I just hope to keept it for consistency.

Also, about the bundling size, I'll test it tomorrow. If you want to take it earlier, you can setup it with:

```bash
npm i typia@next
```

Anyway, as I'm not a frontend developer, not familiar with bundler story. 

By your contributions, I understood how important to support both CJS/ESM for disk space reason. 

Thanks for many ideas and contributions.

**Comment by ryoppippi** [comment]
Thank you for your quick response!!

> 1. Changed tsup to rollup because I'm only familiar with it. It is okay to change again.

If you are familer with it, that is fine! 
I'll check the rollup build result

> 2. About tsx, it can fully replace in current repo

I replaced `ts-node` with `tsx` because it is easy to handle both cjs and esm scripts.
Sometimes `ts-node` fails running scripts with odd errors, so I changed to my familer tool.
If you still want to use `ts-node`, that is totally fine!

**Comment by ryoppippi** [comment]
Also, thank you for adding test for esm.
It looks great

**Comment by samchon** [comment]
As you told that you're planning to adjust monorepo, so that if `rollup` or `ts-node` interrupts it, it is okay to replace it again.

**Comment by ryoppippi** [comment]
> As you told that you're planning to adjust monorepo, so that if rollup or ts-node interrupts it, it is okay to replace it again.

Nice! Thanks

One thing is the result of the build with rollup, but it has been combined into one mjs file!
I would like to change this.

**Comment by ryoppippi** [comment]
Oh, I looked up.
I think for now it is ok for ESM
Thanks.

**Comment by ryoppippi** [comment]
~~Maybe I'll replace rollup to esbuild in the future because the bundle result looks better (for me)~~

Looking at the build results from your rollup, that one looks better with a smaller bundle size. Thanks.
But for now it is fine!!

Thank you for reviewing!

**Review by samchon — APPROVED** [review]
Okay, I will merge at morning.

**Pull request merged**
