### PR TITLE
Make literals work with null

### LINKED ISSUE #685: literals should accept null
## Feature Request
https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGYWgHQA2wMAplKrQM4A8A5AIJdwAfOADsArrVoA+ABQBKIA

Currently null does not work, the extends for literals does not allow for it and when suppressing the error it just omits the value from the array

### PR DESCRIPTION
**Pull request by KristjanTammekivi**
Closes #685

### CODE REVIEW

**Comment by samchon** [comment]
As I have said, null is not a value categorized in atomic, but a type of object.

Therefore, this PR and related issue need to consider about that.

https://github.com/samchon/typia/issues/685#issuecomment-1613383581

**Review by samchon — COMMENTED** [review]
As I have said, null is not a value categorized in atomic, but a type of object.

Therefore, this PR and related issue need to consider about that.

https://github.com/samchon/typia/issues/685#issuecomment-1613383581

**Comment by KristjanTammekivi** [comment]
Can you explain why that matters in the context of this issue/pr?

**Comment by samchon** [comment]
I repeat #685 issue's comment. 

`typia.literals()` function has been designed to get list of constant literal values.

  - `boolean`
  - `number`
  - `bigint`
  - `string`

The `null` value what you want is categorized in `object` type.` It's the problem.

**Comment by KristjanTammekivi** [comment]
No problem then, null is a literal
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/null#description

> The value null is written with a literal: null

Also typeof null is considered a bug that was never fixed https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#typeof_null

And even if it wasn't a literal I would say that that it's an unnecessary self-imposed constraint. I don't think undefined is a literal (although typeof undefined === 'undefined' so going by that standard it might be), but I would argue that literals should work with that as well. Let me talk about my use case.

We use Joi for validation and want to provide a list of valid values for it. Because literals doesn't support null we have to instead do something like the following
```typescript
type ValidValues = 'A' | 'B' | null;
const validValues = [...literals<Exclude<ValidValues, null>>(), null]
```
And this is why I want null to be included

**Comment by samchon** [comment]
Wow, the `null` value to be considered an `object` type was a bug.

Got it. Your PR would be published as a next version `v4.0.5`.

Thanks for contribution.

**Pull request merged**
